#!/usr/bin/env node
/**
 * @my-dsh/rewind-picker build.
 *
 *   lib/index.js  — host half: a stub. Everything is browser-side; the row
 *                   exists so the package qualifies for the client roster.
 *   lib/client.js — client half: src/client/ bundled to CJS and wrapped in the
 *                   `window.__ModuleLoader__.load({ id, factory })` closure the
 *                   harness serves verbatim. React and the framework
 *                   singletons stay external and arrive through the injected
 *                   `require`.
 */
import { build } from 'esbuild'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'))

await mkdir(join(ROOT, 'lib'), { recursive: true })

await build({
  entryPoints: [join(ROOT, 'src', 'index.ts')],
  outfile: join(ROOT, 'lib', 'index.js'),
  format: 'esm',
  platform: 'node',
  target: 'es2022',
  bundle: true,
  external: ['@deepseek-ai/cordis', '@deepseek-ai/dsh-*'],
  sourcemap: false,
})

await build({
  entryPoints: [join(ROOT, 'src', 'client', 'index.ts')],
  outfile: join(ROOT, 'lib', '_client.js'),
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  bundle: true,
  jsx: 'automatic',
  external: ['react', 'react-dom', 'react/jsx-runtime', 'react/jsx-dev-runtime', 'scheduler', '@deepseek-ai/cordis', '@deepseek-ai/dsh-*'],
  logOverride: { 'commonjs-variable-in-esm': 'silent' },
  sourcemap: false,
})

const clientSource = await readFile(join(ROOT, 'lib', '_client.js'), 'utf8')
await rm(join(ROOT, 'lib', '_client.js'))
await writeFile(join(ROOT, 'lib', 'client.js'), [
  `/* ${pkg.name} client bundle — generated by scripts/build.mjs from src/client/ */`,
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} }; var exports = module.exports;',
  clientSource,
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n'))

const host = await readFile(join(ROOT, 'lib', 'index.js'), 'utf8')
const client = await readFile(join(ROOT, 'lib', 'client.js'), 'utf8')
for (const [label, source, expected] of [
  ['lib/index.js', host, ['function apply']],
  ['lib/client.js', client, ['__ModuleLoader__', `id: "${pkg.name}"`, 'conversation.input.overlay', 'fetch("/rewind"']],
]) {
  for (const needle of expected) {
    if (!source.includes(needle)) throw new Error(`build: ${label} is missing ${needle}`)
  }
}
console.log(`built ${pkg.name}:`)
console.log(`  lib/index.js  (host half, stub) ${(host.length / 1024).toFixed(1)} kB`)
console.log(`  lib/client.js (client half, /rewind command + picker) ${(client.length / 1024).toFixed(0)} kB`)
