#!/usr/bin/env node
/**
 * @dsh-pro/routines build.
 *
 *   lib/index.js  — host half: the cron engine. Ported from
 *                   reference/dsh-timer-agent, which ships real sources.
 *   lib/client.js — client half: the settings-page Routines section, ours,
 *                   wrapped in the ModuleLoader factory the harness serves.
 *
 * schemastery is bundled: the harness profile provides @deepseek-ai/schemastery
 * but not the unscoped package this plugin's sources import, so an as-is copy
 * would die at load with ERR_MODULE_NOT_FOUND.
 */
import { build } from 'esbuild'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'))

await mkdir(join(ROOT, 'lib'), { recursive: true })

// ── host half ────────────────────────────────────────────────────────────────
await build({
  entryPoints: [join(ROOT, 'src', 'index.ts')],
  outfile: join(ROOT, 'lib', 'index.js'),
  format: 'esm',
  platform: 'node',
  target: 'es2022',
  bundle: true,
  external: ['@deepseek-ai/cordis', '@deepseek-ai/dsh-*', 'node:*'],
  sourcemap: false,
})

// ── client half ──────────────────────────────────────────────────────────────
const clientEntry = join(ROOT, 'src', 'client', 'index.ts')
if (existsSync(clientEntry)) {
  await build({
    entryPoints: [clientEntry],
    outfile: join(ROOT, 'lib', '_client.js'),
    format: 'cjs',
    platform: 'browser',
    target: 'es2020',
    bundle: true,
    jsx: 'automatic',
    external: ['react', 'react-dom', 'react/jsx-runtime', 'react/jsx-dev-runtime', 'scheduler', '@deepseek-ai/cordis', '@deepseek-ai/dsh-*'],
    logOverride: { 'commonjs-variable-in-esm': 'silent' },
    sourcemap: false,
  })
  const source = await readFile(join(ROOT, 'lib', '_client.js'), 'utf8')
  await rm(join(ROOT, 'lib', '_client.js'))
  await writeFile(join(ROOT, 'lib', 'client.js'), [
    `/* ${pkg.name} client bundle — generated by scripts/build.mjs from src/client/ */`,
    'window.__ModuleLoader__.load({',
    `  id: ${JSON.stringify(pkg.name)},`,
    '  factory: (require) => {',
    '    var module = { exports: {} }; var exports = module.exports;',
    source,
    '    return module.exports;',
    '  },',
    '});',
    '',
  ].join('\n'))
}

// ── smoke checks ─────────────────────────────────────────────────────────────
const host = await readFile(join(ROOT, 'lib', 'index.js'), 'utf8')
for (const needle of ['/api/routines', 'jobs.json']) {
  if (!host.includes(needle)) throw new Error(`build: lib/index.js is missing ${needle}`)
}
if (/from\s*["']schemastery["']/.test(host)) throw new Error('build: schemastery was left external in the host half')
console.log(`built ${pkg.name}:`)
console.log(`  lib/index.js  (host half, cron engine) ${(host.length / 1024).toFixed(0)} kB`)
if (existsSync(join(ROOT, 'lib', 'client.js'))) {
  const client = await readFile(join(ROOT, 'lib', 'client.js'), 'utf8')
  console.log(`  lib/client.js (client half, settings section) ${(client.length / 1024).toFixed(0)} kB`)
}
