#!/usr/bin/env node
/**
 * @my-dsh/workflow build.
 *
 *   lib/index.js  — host half: a stub (the row qualifies the client roster).
 *   lib/fold.js   — the pure fold, emitted separately so the test suite can
 *                   import it without a browser or the ModuleLoader wrapper.
 *   lib/client.js — client half, wrapped in the factory the harness serves.
 */
import { build } from 'esbuild'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'))
await mkdir(join(ROOT, 'lib'), { recursive: true })

await build({
  entryPoints: [join(ROOT, 'src', 'index.ts')],
  outfile: join(ROOT, 'lib', 'index.js'),
  format: 'esm', platform: 'node', target: 'es2022', bundle: true,
  external: ['@deepseek-ai/cordis', '@deepseek-ai/dsh-*'], sourcemap: false,
})

await build({
  entryPoints: [join(ROOT, 'src', 'client', 'fold.ts')],
  outfile: join(ROOT, 'lib', 'fold.js'),
  format: 'esm', platform: 'neutral', target: 'es2022', bundle: true, sourcemap: false,
})

await build({
  entryPoints: [join(ROOT, 'src', 'client', 'index.ts')],
  outfile: join(ROOT, 'lib', '_client.js'),
  format: 'cjs', platform: 'browser', target: 'es2020', bundle: true, jsx: 'automatic',
  external: ['react', 'react-dom', 'react/jsx-runtime', 'react/jsx-dev-runtime', 'scheduler', '@deepseek-ai/cordis', '@deepseek-ai/dsh-*'],
  logOverride: { 'commonjs-variable-in-esm': 'silent' }, sourcemap: false,
})
const source = await readFile(join(ROOT, 'lib', '_client.js'), 'utf8')
await rm(join(ROOT, 'lib', '_client.js'))
await writeFile(join(ROOT, 'lib', 'client.js'), [
  `/* ${pkg.name} client bundle — generated by scripts/build.mjs from src/client/ */`,
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} }; var exports = module.exports;',
  source,
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n'))

const client = await readFile(join(ROOT, 'lib', 'client.js'), 'utf8')
for (const needle of ['__ModuleLoader__', 'tool-workflow/', 'workflow-run']) {
  if (!client.includes(needle)) throw new Error(`build: lib/client.js is missing ${needle}`)
}
const host = await readFile(join(ROOT, 'lib', 'index.js'), 'utf8')
// The host must NOT append session events: plugin-written types are outside
// KNOWN_SESSION_EVENT_TYPES and cannot be marked ignorable, which makes the
// session unreadable rather than merely undrawn.
if (/\.append\(/.test(host)) throw new Error('build: the host half must not append session events')
console.log(`built ${pkg.name}:`)
console.log(`  lib/client.js (progress tree + stock-node suppression) ${(client.length / 1024).toFixed(0)} kB`)
