#!/usr/bin/env node
/**
 * @dsh-pro/deep-research build.
 *
 *   lib/index.js   — host half: the skill and the command expansion.
 *   lib/command.js — the command parser, emitted separately so the test suite
 *                    can import it without the harness or a browser.
 *   lib/client.js  — the `/` menu entry, in the ModuleLoader factory.
 */
import { build } from 'esbuild'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'))
await mkdir(join(ROOT, 'lib'), { recursive: true })

await build({
  entryPoints: [join(ROOT, 'src', 'index.ts')],
  outfile: join(ROOT, 'lib', 'index.js'),
  format: 'esm', platform: 'node', target: 'es2022', bundle: true,
  external: ['@deepseek-ai/cordis', '@deepseek-ai/dsh-*'], sourcemap: false,
})

// The parser alone, with the harness import stubbed: topicOf is pure and worth
// testing, and pulling in dsh-llm to do it would need the whole runtime.
await build({
  entryPoints: [join(ROOT, 'src', 'command.ts')],
  outfile: join(ROOT, 'lib', 'command.js'),
  format: 'esm', platform: 'neutral', target: 'es2022', bundle: true,
  external: ['@deepseek-ai/dsh-llm'], sourcemap: false,
})

await build({
  entryPoints: [join(ROOT, 'src', 'client', 'index.ts')],
  outfile: join(ROOT, 'lib', '_client.js'),
  format: 'cjs', platform: 'browser', target: 'es2020', bundle: true,
  logOverride: { 'commonjs-variable-in-esm': 'silent' }, sourcemap: false,
})
const source = await readFile(join(ROOT, 'lib', '_client.js'), 'utf8')
await rm(join(ROOT, 'lib', '_client.js'))
await writeFile(join(ROOT, 'lib', 'client.js'), [
  `/* ${pkg.name} client bundle — generated by scripts/build.mjs from src/client/ */`,
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} }; var exports = module.exports;',
  source,
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n'))

const host = await readFile(join(ROOT, 'lib', 'index.js'), 'utf8')
// Plugin-authored session events cannot be marked ignorable and make a session
// unreadable; this plugin must never write one.
if (/\.append\(/.test(host)) throw new Error('build: the host half must not append session events')
for (const needle of ['deep-research', 'agent/pre-step', 'requisite variety']) {
  if (!host.toLowerCase().includes(needle.toLowerCase())) {
    throw new Error(`build: lib/index.js is missing ${needle}`)
  }
}
const client = await readFile(join(ROOT, 'lib', 'client.js'), 'utf8')
if (!client.includes('__ModuleLoader__')) throw new Error('build: client bundle is not wrapped')
console.log(`built ${pkg.name}:`)
console.log(`  lib/index.js  (skill + command expansion) ${(host.length / 1024).toFixed(0)} kB`)
console.log(`  lib/client.js (/ menu entry) ${(client.length / 1024).toFixed(1)} kB`)
