#!/usr/bin/env node
/**
 * @dsh-pro/updates build.
 *
 *   lib/index.js  — host half: the release feed, the download, and the swap.
 *   lib/client.js — client half: the settings-page Updates section, wrapped in
 *                   the ModuleLoader factory the harness serves.
 *
 * schemastery and tar are bundled. The profile resolves only what the harness
 * itself ships, so an as-is copy would die at load with ERR_MODULE_NOT_FOUND —
 * and tar in particular cannot be carried instead, because the plugin is
 * installed by copying a directory rather than by npm.
 */
import { build } from 'esbuild'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'))

await mkdir(join(ROOT, 'lib'), { recursive: true })

// ── host half ────────────────────────────────────────────────────────────────
await build({
  entryPoints: [join(ROOT, 'src', 'index.ts')],
  outfile: join(ROOT, 'lib', 'index.js'),
  format: 'esm',
  platform: 'node',
  target: 'es2022',
  bundle: true,
  external: ['@deepseek-ai/cordis', '@deepseek-ai/dsh-*', 'node:*'],
  // tar is CJS and calls require() at runtime; esbuild's ESM output otherwise
  // replaces require with a stub that throws and kills the plugin at import.
  banner: { js: "import { createRequire as __nodeCreateRequire } from 'node:module'\nconst require = __nodeCreateRequire(import.meta.url)" },
  sourcemap: false,
})

// ── client half ──────────────────────────────────────────────────────────────
await build({
  entryPoints: [join(ROOT, 'src', 'client', 'index.ts')],
  outfile: join(ROOT, 'lib', '_client.js'),
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  bundle: true,
  jsx: 'automatic',
  external: ['react', 'react-dom', 'react/jsx-runtime', 'react/jsx-dev-runtime', 'scheduler', '@deepseek-ai/cordis', '@deepseek-ai/dsh-*'],
  logOverride: { 'commonjs-variable-in-esm': 'silent' },
  sourcemap: false,
})
const source = await readFile(join(ROOT, 'lib', '_client.js'), 'utf8')
await rm(join(ROOT, 'lib', '_client.js'))
await writeFile(join(ROOT, 'lib', 'client.js'), [
  `/* ${pkg.name} client bundle — generated by scripts/build.mjs from src/client/ */`,
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} }; var exports = module.exports;',
  source,
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n'))

// ── smoke checks ─────────────────────────────────────────────────────────────
const host = await readFile(join(ROOT, 'lib', 'index.js'), 'utf8')
for (const needle of ['/api/updates', 'api.github.com', 'SHA256SUMS']) {
  if (!host.includes(needle)) throw new Error(`build: lib/index.js is missing ${needle}`)
}
for (const dep of ['tar', 'schemastery']) {
  if (new RegExp(`from\\s*["']${dep}["']`).test(host)) {
    throw new Error(`build: ${dep} is still external — it would not resolve in the profile`)
  }
}
// The whole safety argument rests on refusing an unverified tarball. If this
// string is gone, the refusal branch went with it.
if (!host.includes('checksum-mismatch')) {
  throw new Error('build: the checksum refusal is missing from the host half')
}
const client = await readFile(join(ROOT, 'lib', 'client.js'), 'utf8')
new Function(client)

console.log(`built ${pkg.name}:`)
console.log(`  lib/index.js  (host half, release feed + verified swap) ${(host.length / 1024).toFixed(0)} kB`)
console.log(`  lib/client.js (client half, settings section) ${(client.length / 1024).toFixed(0)} kB`)
