#!/usr/bin/env node
/**
 * @dsh-pro/git-review build.
 *
 *   lib/index.js  — host half: src/host/ bundled to plain ESM.
 *   lib/client.js — client half: src/client/ bundled to CJS, then wrapped in
 *                   `window.__ModuleLoader__.load({ id, factory })`, the
 *                   closure-factory form every `dsh.client` package's
 *                   `./client` export must ship, because the harness serves
 *                   that file verbatim instead of bundling it. React and the
 *                   framework singletons stay external and arrive through the
 *                   injected `require`.
 *
 * Type checking is a separate step (npm run typecheck); this only transpiles
 * and smoke-checks that both outputs parse and the host half has the expected
 * plugin shape.
 */
import { build } from 'esbuild'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'))

await mkdir(join(ROOT, 'lib'), { recursive: true })

await build({
  entryPoints: [join(ROOT, 'src', 'host', 'index.ts')],
  outfile: join(ROOT, 'lib', 'index.js'),
  format: 'esm',
  platform: 'node',
  target: 'es2022',
  bundle: true,
  sourcemap: false,
})

await build({
  entryPoints: [join(ROOT, 'src', 'client', 'index.ts')],
  outfile: join(ROOT, 'lib', '_client.js'),
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  bundle: true,
  external: ['react', '@deepseek-ai/dsh-client-ui-primitives'],
  // The loader wraps this output in a CJS closure that supplies `module` as a
  // local, so the source's `module.exports =` is legitimate here even though
  // esbuild flags it as suspicious under "type": "module".
  logOverride: { 'commonjs-variable-in-esm': 'silent' },
  sourcemap: false,
})

const clientSource = await readFile(join(ROOT, 'lib', '_client.js'), 'utf8')
await rm(join(ROOT, 'lib', '_client.js'))

const bundle = [
  `/* ${pkg.name} client bundle — generated by scripts/build.mjs from src/client/ */`,
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
  clientSource.replace(/\s+$/, '\n'),
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n')
await writeFile(join(ROOT, 'lib', 'client.js'), bundle)

// ---- smoke checks ----
new Function(bundle) // parse only; never executed here (window is undefined)
const host = await import(join(ROOT, 'lib', 'index.js'))
if (typeof host.name !== 'string' || !Array.isArray(host.inject) || typeof host.apply !== 'function') {
  throw new Error('build: host half does not export { name, inject, apply }')
}

console.log(`built ${pkg.name}:`)
console.log('  lib/index.js  (host half, ESM, from src/host/)')
console.log('  lib/client.js (client half, __ModuleLoader__ closure bundle, from src/client/)')
