#!/usr/bin/env node
/**
 * @dsh-pro/notification build.
 *
 *   lib/index.js  — host half: src/ bundled to plain ESM.
 *   lib/client.js — client half: src/client/ bundled to CJS, then wrapped in
 *                   `window.__ModuleLoader__.load({ id, factory })`. The
 *                   harness serves that file verbatim instead of bundling it,
 *                   and the web boot manifest looks a bundle up by the
 *                   INSTALLED PACKAGE NAME — so the id is `@dsh-pro/notification`,
 *                   not the upstream `dsh-at-file`.
 *
 * Harness packages, cordis, and react stay external and arrive through the
 * injected `require`. schemastery and zod are bundled: the profile resolves
 * only what the harness itself ships, and both are pure JS that inlines
 * cleanly.
 */
import { build } from 'esbuild'
import { mkdir, readFile, rm, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const pkg = JSON.parse(await readFile(join(ROOT, 'package.json'), 'utf8'))

await mkdir(join(ROOT, 'lib'), { recursive: true })

const harnessExternal = ['@deepseek-ai/cordis', '@deepseek-ai/dsh-*']

await build({
  entryPoints: [join(ROOT, 'src', 'index.ts')],
  outfile: join(ROOT, 'lib', 'index.js'),
  format: 'esm',
  platform: 'node',
  target: 'es2022',
  bundle: true,
  external: harnessExternal,
  sourcemap: false,
})

await build({
  entryPoints: [join(ROOT, 'src', 'client', 'index.ts')],
  outfile: join(ROOT, 'lib', '_client.js'),
  format: 'cjs',
  platform: 'browser',
  target: 'es2020',
  bundle: true,
  jsx: 'automatic',
  external: [...harnessExternal, 'react', 'react-dom', 'react/jsx-runtime', 'react/jsx-dev-runtime', 'scheduler'],
  // The loader wraps this output in a CJS closure that supplies `module` as a
  // local, so `module.exports =` is legitimate here despite "type": "module".
  logOverride: { 'commonjs-variable-in-esm': 'silent' },
  sourcemap: false,
})

const clientSource = await readFile(join(ROOT, 'lib', '_client.js'), 'utf8')
await rm(join(ROOT, 'lib', '_client.js'))

await writeFile(join(ROOT, 'lib', 'client.js'), [
  `/* ${pkg.name} client bundle — generated by scripts/build.mjs from src/client/ */`,
  'window.__ModuleLoader__.load({',
  `  id: ${JSON.stringify(pkg.name)},`,
  '  factory: (require) => {',
  '    var module = { exports: {} }; var exports = module.exports;',
  clientSource,
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n'))

const host = await readFile(join(ROOT, 'lib', 'index.js'), 'utf8')
const client = await readFile(join(ROOT, 'lib', 'client.js'), 'utf8')
for (const [label, source, expected] of [
  ['lib/index.js', host, ['function apply', 'sessionProjections', "key: \"notification\""]],
  ['lib/client.js', client, ['__ModuleLoader__', `id: "${pkg.name}"`, 'Notification']],
]) {
  for (const needle of expected) {
    if (!source.includes(needle)) throw new Error(`build: ${label} is missing ${needle}`)
  }
}
console.log(`built ${pkg.name}:`)
console.log(`  lib/index.js  (host half, ESM, schemastery + zod inlined) ${(host.length / 1024).toFixed(0)} kB`)
console.log(`  lib/client.js (client half, __ModuleLoader__ closure bundle) ${(client.length / 1024).toFixed(0)} kB`)
